---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
    category: "categories"
baseurl: "http://0987363.github.io/"
title: "heifeng Blog"
canonifyurls: true
copyright: "&copy; 2016. All rights reserved."
paginate: 3
theme: "beg"
params:
    toc: true # optional, When set to TRUE this parameter, table of contents appears in all articles.
...
