---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
      category: "categories"
baseurl: "http://spencerlyon2.github.io/hugo_gh_blog"
title: "heifeng Blog"
canonifyurls: true
...
